services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - bot-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - bot-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge